import json
import logging
from typing import Dict, Any

from ...utils.settings import settings

logger = logging.getLogger(__name__)


def validate_features_json(json_string: str) -> Dict[str, Any]:
    """
    Acts as a mandatory quality check for a JSON string of visual features.

    An agent MUST call this tool immediately after it generates a JSON string
    of creative features. This tool verifies that the agent's output is
    syntactically correct and well-formed before it can be used in subsequent
    steps of a workflow.

    Args:
        json_string: The raw JSON string generated by the agent during the
            feature extraction step.
            Example: '{"animal": false, "human": true, "logo": true}'

    Returns:
        A dictionary detailing the outcome of the validation.
        - On success, the dictionary will have a 'status' of 'success' and a
          'features' key. This 'features' key contains the parsed, validated
          feature dictionary, which is the clean data intended for the next
          step in the workflow.
          Example Success Return:
          {
            "status": "success",
            "features": {"animal": false, "human": true, "logo": true}
          }
        - On failure, the dictionary will have a 'status' of 'error' and an
          'error_message' key with details about the parsing failure. The
          agent should stop the workflow and report this error.
    """
    try:
        if not isinstance(json_string, str):
            raise TypeError("Input must be a string.")

        data = json.loads(json_string)
        return {
            "status": "success",
            "features": data
        }
    except (json.JSONDecodeError, TypeError) as e:
        error_message = f"Validation failed: The provided input is not a valid JSON string. Details: {str(e)}"
        logger.warning(error_message)
        return {
            "status": "error",
            "error_message": error_message
        }


def generate_prediction_sql(features: Dict[str, bool]) -> Dict[str, Any]:
    """
    Generates the BigQuery ML SQL query for performance prediction.

    Args:
        features: A dictionary of boolean features from the features_extraction_agent.

    Returns:
        Dict[str, Any]: A dictionary representing the outcome.
        - On success: `{"status": "success", "sql_query": "SELECT ..."}`
        - On failure: `{"status": "error", "error_message": "Details..."}`
    """
    try:
        project_id = settings.GOOGLE_CLOUD_PROJECT_ID
        dataset_name = settings.BQ_DATASET_NAME
        model_name = settings.BQ_MODEL_NAME

        full_model_id = f"`{project_id}.{dataset_name}.{model_name}`"
        feature_selects = ", ".join(
            f"{str(val).lower()} AS {key}" for key, val in features.items()
        )

        query = f"""
        SELECT
          predicted_is_high_performing AS predicted_class,
          predicted_is_high_performing_probs[OFFSET(1)].prob AS confidence_score
        FROM
          ML.PREDICT(MODEL {full_model_id}, (SELECT {feature_selects}))
        """

        return {"status": "success", "sql_query": query}
    except Exception as e:
        error_msg = "Failed to construct the BigQuery ML prediction SQL query."
        logger.error(f"{error_msg} Details: {e}", exc_info=True)
        return {"status": "error", "error_message": error_msg}
